name: My First Workflow
on:
  push:
    branches:
      - main
jobs:
  first_job:
    name: My First Job
    runs_on: ubuntu_latest
    steps:
      - run: echo "Hello world ${{ github.actor }}."
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - run: tree

      
